### ISSUE TITLE
buttonmap.xml

### ISSUE THREAD

**Issue by zach-morris** [kodi-game/game.libretro.bsnes-mercury-performance#2]
Error in [buttonmap.xml](https://github.com/kodi-game/game.libretro.bsnes-mercury-performance/blob/master/game.libretro.bsnes-mercury-performance/resources/buttonmap.xml#L14)

```
    <feature name="rightbumper" mapto="l"/>
    <feature name="leftbumper" mapto="r"/>
```

should be

```
    <feature name="rightbumper" mapto="r"/>
    <feature name="leftbumper" mapto="l"/>
```

**Comment by garbear** [comment]
done. thanks
